version: '3.1'
services:
  db:
    image: mariadb
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./db-creation-script.sql:/docker-entrypoint-initdb.d/db-creation-script.sql